base_url = "https://rakshagopal.github.io/"
theme = "apollo"
title = "Raksha Gopal"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "light" # light, dark, auto, toggle
comment = false

socials = [
    { name = "orcid", url = "https://orcid.org/0009-0009-7460-5487", icon = "orcid" },
    { name = "email", url = "mailto:raksha.gopal@graduateinstitute.ch", icon = "email"},
    { name = "linkedin", url = "https://www.linkedin.com/in/raksha-gopal-phd/", icon = "linkedin"}
]

menu = [
]

stylesheets = [
    "override.css",
]
