base_url = "https://rakshagopal.github.io/"
theme = "apollo"
title = "raksha gopal"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "light" # light, dark, auto, toggle
comment = false

socials = [
    { name = "twitter", url = "https://twitter.com/gopal_raksha", icon = "twitter" },
    { name = "email", url = "mailto:raksha.gopal@graduateinstitute.ch", icon = "email"},
    { name = "linkedin", url = "https://www.linkedin.com/in/raksha-gopal-phd/", icon = "linkedin"}
]

menu = [
]

stylesheets = [
    "override.css",
]
