base_url = "https://rakshagopal.github.io/"
theme = "apollo"
title = "raksha gopal"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle" # light, dark, auto, toggle
comment = false

socials = [
    { name = "twitter", url = "https://twitter.com/gopal_raksha", icon = "twitter" },
    { name = "email", url = "mailto:raksha.gopal@graduateinstitute.ch", icon = "email"}
]

menu = [
    { name = "about", url = "/", weight = 10},
    { name = "research", url = "/research", weight = 100 },

]

stylesheets = [
    "override.css",
]
