base_url = "https://rakshagopal.github.io/"
theme = "apollo"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle" # light, dark, auto, toggle
comment = false

socials = [
    { name = "twitter", url = "https://twitter.com/gopal_raksha", icon = "twitter" },
]

menu = [

]

stylesheets = [
    "override.css",
]
